import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Criteria from "../components/criteria";
import Graph from "../components/graph";
import Transactions from "../components/transactions";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [walletAddress, setWalletAddress] = useState("");
  useEffect(() => {
    console.log("Wallet address", walletAddress);
  }, [walletAddress]);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div>header</div>
      </header>
      <div className={styles.container}>
        <Criteria onChange={setWalletAddress} />
        <Graph />
        <Transactions />
      </div>
      <footer>
        <div>footer</div>
      </footer>
    </>
  );
}
