import Head from "next/head";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import Criteria from "../components/criteria";
import Graph from "../components/graph";
import Transactions from "../components/transactions";
import { useEffect, useState } from "react";
import fetchTransactionTree from "../tzkt/fetchTransactionTree";
import { validateAddress, ValidationResult } from "@taquito/utils";
import { useRouter } from "next/router";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [transactions, setTransactions] = useState(null);
  const router = useRouter();
  const { address } = useRouter().query;

  useEffect(() => {
    if (validateAddress(address as string) !== ValidationResult.VALID) return;

    fetchTransactionTree(
      [address as string],
      new Date("2020-01-01T00:00:00Z"),
      new Date("2023-01-01T00:00:00Z")
    ).then((nodes) => {
      setTransactions(nodes[0]);
    });
  }, [address]);

  const handleCriteriaChange = (address: string) => {
    if (validateAddress(address as string) !== ValidationResult.VALID) return;

    router.push(`/?address=${address}`);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div>header</div>
      </header>
      <div className={styles.container}>
        <Criteria onChange={handleCriteriaChange} />
        <Graph node={transactions} />
        <Transactions />
      </div>
      <footer>
        <div>footer</div>
      </footer>
    </>
  );
}
